# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'
 
services:

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=MongoDB
    volumes:
      - /volume1/docker/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - indigonet      
      
  indigo-backend:
    image: indigo-backend:v1
    build:
      context: indigo-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - /volume1/documentos/Calibre/EPL:/EPL 
      - /volume1/documentos/Calibre/kindlegen:/kindlegen
    restart: always
    depends_on:
      - mongo
    networks:
      - indigonet
 
  indigo-frontend:
    image: indigo-backend:v2
    build:
      context: indigo-frontend
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://krahen.synology.me:8080/
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - indigo-backend:v2
    networks:
      - indigonet  
   
networks:
  indigonet: 